### ISSUE TITLE
Cannot add to project with react 15.0

### ISSUE THREAD

**Issue by tmey2016** [thereactivestack/meteor-react-router#14]
The default version of react for new meteor projects is 15.0.1. However, this package claims not to be compatible with 15. Output is shown below. Are you planning to update compatibility to react 15? Thank you.

```
$ meteor add reactrouter:react-router
 => Errors while adding packages:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: react 0.14.6, was 15.0.1.
Constraints on package "react":

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

```

**Comment by vlad-dewitt** [comment]
I have same question... Will you do it ?

**Comment by eXon** [comment]
Unless you are not upgrading to meteor 1.3 for some reasons, I recommend that you switch to react-router from NPM.

**Comment by eXon** [comment]
Version has been updated. Thanks for noticing :)
