### ISSUE TITLE
ReactRouter global object not available in 0.1.8

### ISSUE THREAD

**Issue by pmoermans** [thereactivestack/meteor-react-router#4]
When using the latest 0.1.8 version, the ReactRouter object is not available on the window. Rolling back to the 0.1.7 version, the object is available.

Steps to reproduce:
1. create the project as per this post: https://medium.com/@SamCorcos/building-campaignhawk-with-meteor-and-react-part-2-d4551708dcde
2. > meteor
3. observe the error message on the browser console & check the window object
4. > meteor remove reactrouter:react-router
5. > meteor add reactrouter:react-router@=0.1.7
6. > meteor
7. > observe the page is OK in the browser and the window object contains ReactRouter as a global var.

**Comment by eXon** [comment]
I can't reproduce. I'm using 0.1.8 and ReactRouter is there on the client. Can you setup a full working example on a git I can clone?

**Comment by pmoermans** [comment]
Hi Benoit,

Thanks for looking into it !

Here's a complete example you can clone:
https://github.com/pmoermans/bug-repro-reactrouter-not-available.git



Cheers,


On Tue, Sep 29, 2015 at 10:53 PM, Benoit Tremblay <notifications@github.com>
wrote:

> I can't reproduce. I'm using 0.1.8 and ReactRouter is there on the client.
> Can you setup a full working example on a git I can clone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thereactivestack/meteor-react-router/issues/4#issuecomment-144188357>
> .
>



-- 
Pierre Moermans

**Comment by eXon** [comment]
@pmoermans I'm running your project and ReactRouter is available on the client. I'm not sure what's the bug. What OS do you have?

**Comment by eXon** [comment]
@pmoermans Have you tried upgrading your project to the last Meteor version?

**Comment by pmoermans** [comment]
Sorry for the late answer !

I'm running on MacOSX. with node v0.12.7.
I did update to the latest version, but same result.

in the text fie in attachment, you can see the commands I used from cloning
to running and upgrading
also in attachment, the web console screenshot.





On Thu, Oct 1, 2015 at 12:36 PM, Benoit Tremblay <notifications@github.com>
wrote:

> @pmoermans <https://github.com/pmoermans> Have you tried upgrading your
> project to the last Meteor version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thereactivestack/meteor-react-router/issues/4#issuecomment-144690166>
> .
>



-- 
Pierre Moermans

➜  Projects  git clone https://github.com/pmoermans/bug-repro-reactrouter-not-available.git
Cloning into 'bug-repro-reactrouter-not-available'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 22 (delta 0), reused 22 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.
➜  Projects  cd bug-repro-reactrouter-not-available 
➜  bug-repro-reactrouter-not-available git:(master) meteor
[[[[[ ~/Projects/bug-repro-reactrouter-not-available ]]]]]

=> Started proxy.                             
=> Meteor 1.2.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
^C
➜  bug-repro-reactrouter-not-available git:(master) meteor update
                                              
Changes to your project's package version selections from updating the release:
                                              
autopublish             upgraded from 1.0.4-rc.0 to 1.0.4
autoupdate              upgraded from 1.2.3-rc.1 to 1.2.3
babel-compiler          upgraded from 5.8.22-rc.0 to 5.8.24_1
babel-runtime           upgraded from 0.1.4-rc.0 to 0.1.4
base64                  upgraded from 1.0.4-rc.0 to 1.0.4
binary-heap             upgraded from 1.0.4-rc.0 to 1.0.4
blaze                   upgraded from 2.1.3-rc.0 to 2.1.3
blaze-html-templates    upgraded from 1.0.1-rc.0 to 1.0.1
blaze-tools             upgraded from 1.0.4-rc.0 to 1.0.4
boilerplate-generator   upgraded from 1.0.4-rc.0 to 1.0.4
caching-compiler        upgraded from 1.0.0-rc.0 to 1.0.0
caching-html-compiler   upgraded from 1.0.1-rc.0 to 1.0.2
callback-hook           upgraded from 1.0.4-rc.0 to 1.0.4
check                   upgraded from 1.0.6-rc.0 to 1.0.6
coffeescript            upgraded from 1.0.8-rc.2 to 1.0.10
ddp                     upgraded from 1.2.1-rc.0 to 1.2.2
ddp-client              upgraded from 1.2.1-rc.1 to 1.2.1
ddp-common              upgraded from 1.2.1-rc.0 to 1.2.1
ddp-server              upgraded from 1.2.1-rc.1 to 1.2.1
deps                    upgraded from 1.0.8-rc.0 to 1.0.9
diff-sequence           upgraded from 1.0.1-rc.0 to 1.0.1
ecmascript              upgraded from 0.1.3-rc.1 to 0.1.5
ecmascript-collections  upgraded from 0.1.5-rc.1 to 0.1.6
ejson                   upgraded from 1.0.7-rc.0 to 1.0.7
es5-shim*               upgraded from 0.1.0-rc.0 to 4.1.13
fastclick               upgraded from 1.0.7-rc.0 to 1.0.7
geojson-utils           upgraded from 1.0.4-rc.0 to 1.0.4
hot-code-push           upgraded from 1.0.0-rc.0 to 1.0.0
html-tools              upgraded from 1.0.5-rc.0 to 1.0.5
htmljs                  upgraded from 1.0.5-rc.1 to 1.0.5
http                    upgraded from 1.1.1-rc.1 to 1.1.1
id-map                  upgraded from 1.0.4-rc.0 to 1.0.4
insecure                upgraded from 1.0.4-rc.0 to 1.0.4
jquery                  upgraded from 1.11.4-rc.0 to 1.11.4
launch-screen           upgraded from 1.0.3-rc.1 to 1.0.4
livedata                upgraded from 1.0.14-rc.0 to 1.0.15
logging                 upgraded from 1.0.8-rc.1 to 1.0.8
meteor                  upgraded from 1.1.7-rc.1 to 1.1.9
meteor-base             upgraded from 1.0.1-rc.0 to 1.0.1
minifiers               upgraded from 1.1.6-rc.1 to 1.1.7
minimongo               upgraded from 1.0.9-rc.0 to 1.0.10
mobile-experience       upgraded from 1.0.1-rc.0 to 1.0.1
mobile-status-bar       upgraded from 1.0.5-rc.1 to 1.0.6
mongo                   upgraded from 1.1.1-rc.2 to 1.1.2
mongo-id                upgraded from 1.0.1-rc.0 to 1.0.1
npm-mongo               upgraded from 1.4.39-rc.0_1 to 1.4.39_1
observe-sequence        upgraded from 1.0.7-rc.0 to 1.0.7
ordered-dict            upgraded from 1.0.4-rc.0 to 1.0.4
promise                 upgraded from 0.4.8-rc.0 to 0.5.0
random                  upgraded from 1.0.4-rc.0 to 1.0.4
reactive-dict           upgraded from 1.1.1-rc.0 to 1.1.2
reactive-var            upgraded from 1.0.6-rc.0 to 1.0.6
reload                  upgraded from 1.1.4-rc.0 to 1.1.4
retry                   upgraded from 1.0.4-rc.0 to 1.0.4
routepolicy             upgraded from 1.0.6-rc.0 to 1.0.6
session                 upgraded from 1.1.1-rc.0 to 1.1.1
spacebars               upgraded from 1.0.7-rc.0 to 1.0.7
spacebars-compiler      upgraded from 1.0.7-rc.0 to 1.0.7
standard-minifiers      upgraded from 1.0.0-rc.1 to 1.0.1
templating              upgraded from 1.1.2-rc.3 to 1.1.4
templating-tools        upgraded from 1.0.0-rc.0 to 1.0.0
tracker                 upgraded from 1.0.8-rc.0 to 1.0.9
ui                      upgraded from 1.0.7-rc.0 to 1.0.8
underscore              upgraded from 1.0.4-rc.0 to 1.0.4
url                     upgraded from 1.0.5-rc.0 to 1.0.5
webapp                  upgraded from 1.2.2-rc.1 to 1.2.2
webapp-hashing          upgraded from 1.0.4-rc.0 to 1.0.5

                                              
* These packages have been updated to new versions that are not backwards
compatible.
bug-repro-reactrouter-not-available: updated to Meteor 1.2.0.2.
                                              
Changes to your project's package version selections from updating package versions:
                                              
cosmos:browserify  upgraded from 0.5.0 to 0.5.1
jsx                upgraded from 0.2.0 to 0.2.1
react              upgraded from 0.1.11 to 0.1.13
react-meteor-data  upgraded from 0.1.7 to 0.1.9

                                              
The following top-level dependencies were not updated to the very latest version available:
 * reactrouter:react-router 0.1.8 (0.1.9 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * cosmos:browserify 0.5.1 (0.8.0 is available)
To update one or more of these packages, pass their names to `meteor update`.
➜  bug-repro-reactrouter-not-available git:(master) ✗ meteor
[[[[[ ~/Projects/bug-repro-reactrouter-not-available ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/

**Comment by eXon** [comment]
You might want to update react-router to the last version (0.1.9), I've updated browserify and I think it was causing some problems.

**Comment by pmoermans** [comment]
Upgrading to 0.1.9 solved the issue! Thanks a lot.
