### ISSUE TITLE
Router redirecting to http://localhost:3000/#/?_k=tnocl5

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/meteor-react-router#5]
Hi

I have a default route configured as such:

```
React.render((
  <Router>
    <Route path="/" component={App}>
      <IndexRoute component={Main} />
    </Route>
  </Router>
), document.body)
```

But it keeps redirecting me on localhost to `http://localhost:3000/#/?_k=7xfemo`

Where the key is randomly generated id, meaning it is different with every page reload,
I am using `https://github.com/thereactivestack/kickstart-simple` boilerplate.

Just a side-note, this does not happen with react-router-ssr

Thanks

**Comment by tomitrescak** [comment]
Found the culprit. When defined router with history, all works well:

```
const history = ReactRouter.history.useQueries(ReactRouter.history.createHistory)();

Meteor.startup(function() {
  React.render((
    <Router history={history}>
      <Route path="/" component={App}>
        <IndexRoute component={Main} />
      </Route>
    </Router>
  ), document.body);
});
```

**Comment by daver182** [comment]
For anyone having the same problem, this solution didn't work for me, I was getting a "Browser history needs a DOM" error, so I have to put it inside the startup function, if anyone knows why I would like to know.

````

Meteor.startup(function() {
  const history = ReactRouter.history.useQueries(ReactRouter.history.createHistory)();
  React.render((
    <Router history={history}>
      <Route path="/" component={App}>
        <IndexRoute component={Main} />
      </Route>
    </Router>
  ), document.body);
});

````
