### ISSUE TITLE
Could this work without react-runtime@0.13 ?

### ISSUE THREAD

**Issue by skosch** [thereactivestack/meteor-react-router#6]
I realize this question is totally off the wall, but would it feasible to decouple this from [Meteor's react-packages](https://github.com/meteor/react-packages) altogether (besides the mixin, I guess) and have users bring their own React? (I.e. via webpack).

Now that we have React, I'm really only using Meteor for its DDP and user account system, and having to wait e.g. for the React Meteor wrappers to be updated to 0.14 is a bit frustrating.

I've tried to muck around with this package and its `-ssr` cousin, but I haven't yet been able to get all the pieces to fit. I'd be really grateful for any pointers! :)

**Comment by skosch** [comment]
I've decided to remove both `meteor-react-router` and `meteor-react-router-ssr` from my project entirely and go with with webpack everything. My only candidates for SSR are public-facing pages anyway, and they don't need any patching of Collection functions, so I can just use what react-router provides out of the box. Thanks for your efforts again Benoît, sorry for the noise!

**Comment by eXon** [comment]
Their is really no reason to use meteor-react-router if you don't use react-runtime. React 0.14 is going to be available in about a week btw ;)
