### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by MasterAM** [thereactivestack/meteor-react-router#8]
React Router v1.0.0 was released with a lot of API changes.

Do you have an update planned? If so, I think that matching the package and release versions will make it easier to know which version of the router we're using :smile: 

Thanks for the great work in general.

**Comment by eXon** [comment]
This package is currently on 1.0.0-rc4 so their is no breaking changes for 1.0. I'll update the version asap :)

**Comment by MasterAM** [comment]
It's embarrassing, but I simply forgot to explicitly import `IndexRoute`, which made me think that it is the older version... Thanks for the update, though!

**Comment by eXon** [comment]
It has been updated to the official 1.0.0 (last version :))
